fix: Several localisation issues.
GEWIS/sudosos-frontend pull request #179
Opened 2024-05-21 11:06 UTC by CodeNamedRobin

Fixes #175 
Fixes #165 
Fixes #158

2024-05-21 12:58 UTC, SuperVK commented
wait is this PR branched from #155 ?

2024-05-21 16:14 UTC, CodeNamedRobin commented
@SuperVK could be? Wouldn't really matter I guess but I might have made a mistake when branching.

2024-05-21 16:53 UTC, SuperVK requested changes

2024-05-21 16:53 UTC, SuperVK commented on src/components/Mutations/MutationsTableComponent.vue
> -            mutation.data.moment.toLocaleDateString('nl-NL', {
not sure if I fully agree with this, in English mode (for 90% of the users), the date will be American, which is date / month / year, which is super confusing. Maybe "correct" as you have selected that locale, but for most of our userbase not the preferred option.

2024-05-21 16:53 UTC, SuperVK commented on src/main.ts
> -    locale: localStorage.getItem('locale') || 'en',
Don't agree, main language of GEWIS is english, we don't want internationals searching on how to change the language

2024-05-21 16:55 UTC, SuperVK commented
does not fully fix #158 
![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/31625323/9b7914f8-3b00-4561-b5b5-36892c9fd3f9)

2024-05-21 17:25 UTC, tomudding commented on src/components/Mutations/MutationsTableComponent.vue
> -            mutation.data.moment.toLocaleDateString('nl-NL', {
I agree with Victor that the `short` variant should be `YYYY-MM-DD`.

2024-05-21 18:45 UTC, CodeNamedRobin commented on src/components/Mutations/MutationsTableComponent.vue
> -            mutation.data.moment.toLocaleDateString('nl-NL', {
Fixed!

2024-05-21 18:46 UTC, CodeNamedRobin commented on src/main.ts
> -    locale: localStorage.getItem('locale') || 'en',
Fixed

2024-05-21 18:59 UTC, CodeNamedRobin commented
> does not fully fix #158 ![image](https://private-user-images.githubusercontent.com/31625323/332512802-9b7914f8-3b00-4561-b5b5-36892c9fd3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTcxNzEsIm5iZiI6MTcxNjMxNjg3MSwicGF0aCI6Ii8zMTYyNTMyMy8zMzI1MTI4MDItOWI3OTE0ZjgtM2IwMC00NTYxLWI1YjUtMzY4OTJjOWZkM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE4NDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzhkYzI1M2Y1NDk4YzFmMjU1MTNlYWVjMTEzNTg4YTZmOGU2YTljNWZiMTRiMWE0MzdkZDc1ODZjYmQxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M2tFoRkvLOIybeo4CWoCvmwhLTl2S2UCY26-Ru0Q9uI)

This is now fixed!

2024-05-21 21:33 UTC, SuperVK commented
![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/31625323/cebbec1c-6ac3-46b7-8704-52c04312ca03)
This does not load right now :(

2024-05-22 19:17 UTC, SuperVK approved these changes

2024-05-22 19:36 UTC, merged