Improved POS login
GEWIS/sudosos-frontend pull request #204
Opened 2024-06-08 19:30 UTC by SuperVK

Improved the styling of the keypad, and improved and changed rendering of the banners

# Description
The styling of the keypad has now been changed to remove the continue button in favor of being able to tap the userid and passcode field. As well as updated buttons.

Furthermore the banners rendering have changed. First of all, banners that would not fit the size are now in their original aspect ratio, and are rescaled to fit in the slot, with the excess being filled by the poster background from TVPC/aurora. Furthermore the active checkbox is now to override when set to false, instead of override when set to true. Finally banners without an image are not rendered anymore, but instead skipped.

![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/f7cf3f9e-3d67-4067-9804-ef0fcb30683f)

## Related issues/external references
No related issues.

## Types of changes

- Bug fix _(non-breaking change which fixes an issue)_
- New feature _(non-breaking change which adds functionality)_
- Design changes

2024-06-10 13:34 UTC, JustSamuel commented
Single Responsibility: I have almost no remarks on the banner side, but some small on the extra login thingy, so maybe these should have been 2 PR's.

2024-06-10 13:38 UTC, JustSamuel requested changes
In general I agree, but I do think that the "how to login" is cramped between the keypad and the banner. Maybe move it some where else? bottom left in the form of an icon + image?

2024-06-10 13:38 UTC, JustSamuel commented on apps/dashboard/src/components/BannerItemComponent.vue
> +   ${banner.value.duration != 1 ? t('banner.seconds') : t('banner.second')}`;
I know this isn't your original code; but we should use pluralization instead https://vue-i18n.intlify.dev/guide/essentials/pluralization

2024-06-10 13:44 UTC, SuperVK commented
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/d7d543a1-c4ab-4860-a88c-f2a6a30ad890)
I was thinking of 3 or 4 myself first. Do you mean 1 or 2 in for the bottom? And then like a question mark or exclamation mark icon?

2024-06-10 14:04 UTC, JustSamuel commented
> I was thinking of 3 or 4 myself first. Do you mean 1 or 2 in for the bottom? And then like a question mark or exclamation mark icon?

I think 1 would be best; but maybe show the options to some different people?

2024-06-10 14:12 UTC, SuperVK commented
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/6e52159d-845c-45ec-af4f-50c7cb7ccb52)
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/7aff6bca-4fd6-40eb-83d6-77ff2d485b27)
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/0d669bd0-9eb5-4d27-9d59-caaf8b4fa633)
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/d02b1a45-00d9-475f-8d62-be4fbc0ffea6)

2024-06-11 09:20 UTC, JustSamuel approved these changes
LGTM

2024-06-11 09:28 UTC, merged