Feature: manage products rework
GEWIS/sudosos-frontend pull request #207
Opened 2024-06-13 12:58 UTC by JustSamuel

Manage Products View and Components Rework

# Description
This PR completely overhauls the product management by merging `ContainerAssignProductDialog`, `ProductCreateComponent` and `ProductDialogComponent` into a single, unified component. 

To this end the PR also contains a rework of the container and product store which bring about easy deep reactivity and easier lazy loading. 

Details, screenshots and examples will be added,

## Related issues/external references
#119 
## Types of changes
- Bug fix _(non-breaking change which fixes an issue)_
- New feature _(non-breaking change which adds functionality)_
- Documentation improvement

2024-06-14 14:21 UTC, SuperVK commented
When adding an existing product to a container, the modal doesn't close

Changing the picture does require a reload of the page to be shown in the general overview.

Would be nice if your cursor would show pointer on hover of products in containers.

Sometimes I had issues with created products, where the modal wouldn't close, but turns out it did make the product. Can't reproduce anymore atm tho

![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/5417b5ec-2497-409a-b66e-561aa6928889)
Would it be possible to remove this form validation when selecting a product?

![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/d00b1061-931c-4043-aa2a-60dab3d70253)
Might be nice to give price, alc, and VAT some more room in favor of name.

Changing properties of a product does not work from the container overview.

Do we maybe want to change the edit mode in the product overview to also give the same modal as editing in the container overview? Preventing issues such as below:
![image](https://github.com/GEWIS/sudosos-frontend/assets/31625323/5c4cb0ad-3656-44f6-984d-e0c42bba53b5)


Updating most properties from editing in product overview do reflect in the container overview, but VAT does not.

2024-06-14 15:02 UTC, SuperVK commented
Oh btw besides all these comments: Already very good looking, the reactive updating is *chefs kiss*

2024-06-16 12:32 UTC, CodeNamedRobin requested changes
Overall this rework is pretty great, however still unusable on mobile.

2024-06-16 12:32 UTC, CodeNamedRobin commented on apps/dashboard/src/components/ContainerCardComponent.vue
> +<!--    <TabView :active-index=1 class="hidden md:block" :scrollable="true">-->
Commented Code

2024-06-16 12:32 UTC, CodeNamedRobin commented on apps/dashboard/src/components/ContainerCardComponent.vue
> +<!--    TODO re-add newContainer button -->
Issue or fix

2024-06-16 12:36 UTC, CodeNamedRobin commented
Having products appear in one column might not be the greatest use of space.
![image](https://github.com/GEWIS/sudosos-frontend/assets/12692018/0ee0f744-df15-4970-a3fe-8043ff1807de)
Also, in the products table things overlap, and the create button is outside of the table
![image](https://github.com/GEWIS/sudosos-frontend/assets/12692018/8c7f13b9-92f4-4a91-9a5c-342a60e3a4c0)
The ProductCreateModal is outside of the screen currently.
![image](https://github.com/GEWIS/sudosos-frontend/assets/12692018/e50ba0e9-2e8b-44e7-b08e-e034a30c5d4d)

2024-06-16 12:37 UTC, CodeNamedRobin commented
You can't choose containers on create pos view
![image](https://github.com/GEWIS/sudosos-frontend/assets/12692018/4d3aa3ac-f22f-4597-8976-66b1fac57504)

2024-06-18 21:31 UTC, SuperVK commented
The create products button on all products has broken when it is the first thing you click after reloading the page, after which the whole page goes into a panick, and nothing works anymore. If you try to edit a product first, and then click create, it will show the last edited product.

VAT is still showed as the default from the product category related to the product, even if the database information for that product is different from it.

2024-06-19 07:58 UTC, SuperVK commented
Not that high priority but still nice: Right now the behavior when the network is offline is kinda wonky, the modal does not close, which is somewhat fair, but it might be nice to handle this with the toast services. Furthermore, the modal does refuse to close, but the product _is_ added to the container, until refreshed atleast.

2024-06-19 12:53 UTC, JustSamuel commented
>  The create button could use some space from the containers
I like it as a kinda "bookmark"

2024-06-19 14:52 UTC, SuperVK commented
> > The create button could use some space from the containers
> > I like it as a kinda "bookmark"

I see what you mean, but that is inconsistent with the styling in the rest of the app(, and I think for the bookmark to look good you want to remove the radius on the bottom).

2024-06-19 19:40 UTC, SuperVK approved these changes
Missing one translation, but besides that, I think it's pico bello!

2024-06-19 19:40 UTC, SuperVK commented on apps/dashboard/src/components/ProductCardComponent.vue
> +  <CardComponent header="all products" class="w-full">
Needs translations

2024-06-19 20:46 UTC, SuperVK approved these changes
LGTM!

2024-06-21 12:16 UTC, merged