Feature/dashboard maintenance screen
GEWIS/sudosos-frontend pull request #422
Opened 2024-10-20 15:37 UTC by RubenLWF

# Description

This PR adds a maintenance screen that will be displayed when SudoSOS is under maintenance.
This information is fetched from the `rootApi.ping()` endpoint.

The maintenance screen will look like this:
![image](https://github.com/user-attachments/assets/1e73e31f-9c73-4535-9882-60dc9d4b6c43)

## Related issues/external references

## Types of changes

- New feature _(non-breaking change which adds functionality)_

2024-10-21 08:59 UTC, SuperVK requested changes

2024-10-21 08:59 UTC, SuperVK commented on apps/dashboard/src/main.ts
> +}
Okay I think I hindsight I gave you the wrong suggestion in the working moment. I would make this:
```suggestion
beforeLoad().then(() => {
    app.mount('#app');
});
```
or 
```suggestion
await beforeLoad()
app.mount('#app');

```

2024-10-21 08:59 UTC, SuperVK commented on apps/dashboard/src/utils/beforeLoadUtil.ts
> +  await populateStoresFromToken(apiService);
And here catch the possible error from `populateStoresFromToken` and log out if need:
```js
clearTokenInStorage();
const authStore = useAuthStore();
authStore.logout();
```

2024-10-21 21:34 UTC, SuperVK approved these changes

2024-10-21 21:50 UTC, JustSamuel commented
Do we also want to include the logic for admin bypass here? Or just keep that at the API for now

2024-10-29 09:45 UTC, JustSamuel requested changes

2024-10-29 09:45 UTC, JustSamuel commented on apps/dashboard/src/main.ts
> +app.mount('#app');
Top level await is not allowed, use a `.then` instead.

(this is also why you have a build error)

@SuperVK

2024-10-29 21:41 UTC, JustSamuel approved these changes

2024-10-29 21:48 UTC, merged

2024-10-30 17:27 UTC, RubenLWF commented
Does something similar also need to be made for the POS?

I heard @SuperVK mention something about that a websocket first needs to be implemented in the backend

2024-10-30 17:59 UTC, JustSamuel commented
Kinda, the POS is not very often refreshed, so my idea was to have a websocket which indicates if the backend is up.
If you feel like taking a deeper dive in the backend, I have a branch which has an almost working version 👀