Feature/create invoice overview
GEWIS/sudosos-frontend pull request #465
Opened 2024-11-25 11:10 UTC by Jobbiesaus

# Description
Added an overview of the open invoice accounts at the top of the invoice tab.

## Related issues/external references
#461

## Types of changes
- New feature _(non-breaking change which adds functionality)_

2024-11-25 15:29 UTC, JustSamuel requested changes
Solid work! love that you added the notifications ❤️

2024-11-25 15:29 UTC, JustSamuel commented on apps/dashboard/src/components/FindUser.vue
> +}
?

2024-11-25 15:29 UTC, JustSamuel commented on apps/dashboard/src/mixins/openInvoiceAccountsMixin.ts
> +    );
is this fast enough? maybe we should add a dedicated endpoint for this in the backend?

2024-12-18 17:38 UTC, Jobbiesaus commented on apps/dashboard/src/components/FindUser.vue
> +}
This was my IDE who did something weird for me. Should be gone now.

2024-12-18 18:03 UTC, JustSamuel approved these changes

2024-12-18 18:09 UTC, Jobbiesaus commented on apps/dashboard/src/mixins/openInvoiceAccountsMixin.ts
> +    );
Let's try it out

2024-12-18 18:10 UTC, merged