Feature/profile
GEWIS/sudosos-frontend pull request #72
Opened 2023-10-24 20:39 UTC by JorisParee

pin, password and api key are working in profile view. local user information lacks but has a issue

2023-10-25 13:50 UTC, CodeNamedRobin commented
Noted to fix #47.

2023-10-25 14:49 UTC, CodeNamedRobin requested changes
There are some things that need to be fixed, both in code style and in aesthetics. I also wonder if this layout of the cards is the best. It right now feels like it is crammed to the left side.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +    console.log(err);
Please either wait for the merge of #74 and then implement that error handling here or already merge #74 into your own branch to use that error handling.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +      toast.add({ severity: "success", summary: "Success", detail: `${t('profile.Your new key is')} \n ${res.key} \n ${t('profile.Kay is not saved')}` });
Formatting.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +  <card-component :header="t('profile.Get api key')">
Please use indices that are camelCase and shorter. The content should not be the key.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +      <p>{{ $t('profile.Note old api key will get removed') }}</p>
Idem.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +      <Button severity="danger" :label="t('profile.Get new API key')" @click="updateApiKey" />
Idem.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +function validateFirstName(checkFirstName: string) {
For this we don't need custom validators. See [yup](https://github.com/jquense/yup#schema-defaults).

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +function validateLastName(checkLastName: string) {
Idem.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +function validateEmail(checkEmail: string) {
Idem.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +    //TODO update info
Reference the issue or fix.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +    toast.add({ severity: "error", summary: "failed", detail: 'fill in correct info', life: 3000 });
Formatting.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +      <small v-if="!isLocal">!This account is not managed trhoug SudoSOS!</small>
Hardcoded text and spelling mistake.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +  <card-component :header="'Change user info'">
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +        <p>FirstName</p>
Hardcoded text

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +        <p>Last name</p>
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +        <p>Email adress</p>
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +        <Button severity="danger" :disabled="true" label="Update user info" @click="changeUserInfo"/>
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeInfoComponent.vue
> +  <Toast />
This toast is not needed anymore after mergin #74. Just to keep in mind.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +    //TODO set password requirements
Make issue or fix.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +function validatePassword(checkPassword: string) {
Custom validators are not needed, as per earlier comment.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +function validateConfirmPassword(checkConfirmPassword: string) {
Custom validators are not needed.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +      console.error(err);
Again #74.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +    toast.add({ severity: "error", summary: "failed", detail: t('profile.Incorrect passwords submitted'), life: 3000 });
Hardcoded text in summary.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +        <p>Password</p>
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +        <p>Confirm password</p>
Hardcoded text.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangeApiKeyComponent.vue
> +      toast.add({ severity: "success", summary: "Success", detail: `${t('profile.Your new key is')} \n ${res.key} \n ${t('profile.Kay is not saved')}` });
Hardcoded text in summary, fixed when #74 is merged.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +function validatePin(checkInputPin: string){
Custom validators.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +function validateConfirmPin(checkConfirmPin: string){
Idem.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +      // Error
Error handling, again #74.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +      toast.add({ severity: "success", summary: "success", detail: t('profile.Pin code updated')  });
Hardcoded text in summary.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +    toast.add({ severity: "error", summary: "failed", detail: t('profile.Incorrect pin code submitted'), life: 3000 });
Hardcoded text in summary.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/components/ChangePinComponent.vue
> +    <Toast />
Again, toast not needed if #74 is merged.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/locales/en.json
I already mentioned this, but the keys should be in camelCase and be short and to the point. Actual content should be in the values.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/locales/en.json
Are all these added keys also in nl.json?

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/views/ProfileView.vue
Can you format the content in <template> tag? There is a lot of white space for no apparent reason.

2023-10-25 14:49 UTC, CodeNamedRobin commented on src/views/ProfileView.vue
> +apiService.user.updateUser(0, {
??

2023-12-04 12:59 UTC, JustSamuel requested changes
Only a single mistake

2023-12-04 12:59 UTC, JustSamuel commented on src/components/ChangePasswordComponent.vue
> +      userStore.getCurrentUser.user?.id, {password: values.password}).then(() => {
missing a .catch

2023-12-06 12:07 UTC, CodeNamedRobin commented on src/components/ChangePasswordComponent.vue
> +      userStore.getCurrentUser.user?.id, {password: values.password}).then(() => {
Fixed

2023-12-06 12:34 UTC, CodeNamedRobin approved these changes
LGTM!

2023-12-06 12:52 UTC, CodeNamedRobin commented
Fixes #73

2023-12-11 19:32 UTC, JustSamuel approved these changes
LGTM

2023-12-11 19:38 UTC, merged