Transaction / Mutation Table
GEWIS/sudosos-frontend pull request #80
Opened 2023-12-02 21:32 UTC by BHenkemans

2023-12-06 12:52 UTC, CodeNamedRobin commented
Fixes #80

2023-12-06 13:42 UTC, CodeNamedRobin commented
@BHenkemans fine mutations are not implemented yet.

2023-12-11 09:14 UTC, CodeNamedRobin commented
Right now the way the table works does not fully comply with existing pages. POSInfoView and SingleUserView get their transaction in a different way than what MutationTableComponent wants. This needs to be fixed before merging.

2023-12-12 08:34 UTC, CodeNamedRobin commented
Still needs:

- [ ] Pagination
- [ ] Deleting of single transactions
- [ ] (Lower priority) filtering and sorting

2023-12-12 18:30 UTC, JustSamuel requested changes
Added some small fixes and left a small remark.

2023-12-12 18:30 UTC, JustSamuel commented on src/utils/paginationUtil.ts
> +// import type { PaginatedFinancialMutationResponse } from "@sudosos/sudosos-client";
What happend here

2023-12-12 18:55 UTC, JustSamuel approved these changes
lgtm

2023-12-12 19:03 UTC, merged